services:
  ch3f:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      - kitchen
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure
    volumes:
      - container_storage:/storage
      - /var/run/docker.sock:/var/run/docker.sock

  client:
    build:
      context: .
      dockerfile: cmd/docker/Dockerfile
    platform: linux/arm64  # für explizite Plattform (optional, aber empfohlen)
    image: ch3fs-client      # optional, damit der Name gesetzt wird
    networks:
      - kitchen
    depends_on:
      - ch3f

      
volumes:
  container_storage:
    driver: local
networks:
  kitchen:
    name: kitchen