services:
  ch3f:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      - kitchen
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure

networks:
  kitchen:
    name: kitchen