services:
  ch3f:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    env_file:
      - docker/.env
    networks:
      - kitchen
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

networks:
  kitchen:
    name: kitchen